In [53]:
#1
import numpy as np

In [54]:
#2
np.__version__

'2.3.5'

In [55]:
#3
#create a null vector of size 10
null_vector = np.zeros(10, dtype = np.int32)
null_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [56]:
#4
#find the memory size of an array
random_array = np.random.rand(1,3) # default = float 64
# so each element has 64/8 = 8 bytes
# this araray has 3 * 8 = 24 bytes
random_array.nbytes

24

In [57]:
# How to get the documentation of the numpy add function from the command line?
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` 

In [58]:
# 6. Create a null vector of size 10 but the fifth value which is 1
vector = np.zeros((10), dtype = np.int16)
vector[4] = 1
vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int16)

In [59]:
# 7. Create a vector with values ranging from 10 to 49 
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [60]:
 # 8. Reverse a vector (first element becomes last)

In [61]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 
matrix = np.arange(9).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] 
"""np.nonzero(), """

#in-efficient approach
vector = np.array([1,2,0,0,4,0])
length = vector.size
indices = []
for i in range(length):
    if vector[i] != 0:
        indices.append(i)

#np.nonzero
##help(np.nonzero)
indices = np.nonzero(vector)[0]
indices

array([0, 1, 4])