In [2]:
#1
import numpy as np

In [54]:
#2
np.__version__

'2.3.5'

In [55]:
#3
#create a null vector of size 10
null_vector = np.zeros(10, dtype = np.int32)
null_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [56]:
#4
#find the memory size of an array
random_array = np.random.rand(1,3) # default = float 64
# so each element has 64/8 = 8 bytes
# this araray has 3 * 8 = 24 bytes
random_array.nbytes

24

In [57]:
# How to get the documentation of the numpy add function from the command line?
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` 

In [58]:
# 6. Create a null vector of size 10 but the fifth value which is 1
vector = np.zeros((10), dtype = np.int16)
vector[4] = 1
vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int16)

In [59]:
# 7. Create a vector with values ranging from 10 to 49 
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [60]:
 # 8. Reverse a vector (first element becomes last)

In [61]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 
matrix = np.arange(9).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] 
"""np.nonzero(), """

#in-efficient approach
vector = np.array([1,2,0,0,4,0])
length = vector.size
indices = []
for i in range(length):
    if vector[i] != 0:
        indices.append(i)

#np.nonzero
##help(np.nonzero)
indices = np.nonzero(vector)[0]
indices

array([0, 1, 4])

In [6]:
#create 3x3 identiy matrix
identiy = np.identity(3)
identiy

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# 12. Create a 3x3x3 array with random values
random_number_generator = np.random.default_rng()
random_array = random_number_generator.random(size= (3,3,3))
random_array

array([[[0.74711219, 0.15192843, 0.21585145],
        [0.98114814, 0.4084269 , 0.33635681],
        [0.40026613, 0.81603902, 0.26435401]],

       [[0.64290216, 0.69937955, 0.92015698],
        [0.83793861, 0.92133309, 0.82306497],
        [0.30821583, 0.28723035, 0.33802753]],

       [[0.34812082, 0.63666816, 0.2248604 ],
        [0.86396492, 0.90852883, 0.6556038 ],
        [0.69564112, 0.55845712, 0.59607243]]])

In [14]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values
rng = np.random.default_rng()
random_10x10 = rng.random(size = (10,10)) *100
print('array: ', random_10x10)
min_val = np.amin(random_10x10)
max_val = np.amax(random_10x10)
print('min value: ',min_val)
print('max value: ', max_val)

array:  [[10.25583145 88.17740959 61.45813467  0.38612389 40.71269314 96.91662572
  86.8600102  48.9541035  61.87673931 35.87611216]
 [39.84085411  6.51730434 50.8575602  11.43610943 34.52887129 62.97189783
  17.9277601  45.12924467 63.6144152  84.32129451]
 [38.12681792 93.38298711 96.05531507 78.69774304 85.59173622 74.5617519
  26.33998191 91.41966388 14.45054196 41.64514993]
 [ 5.18753274 36.96696964 91.52094809 71.04581159 58.60249243 48.70409816
   5.62145918 81.64857388 29.66606935 44.46470383]
 [62.55840609  6.78531279 35.36636334 73.95207304 33.24409478 45.63933913
   6.22324239 50.70864684 34.84674131 82.27867715]
 [79.67429665 31.21284588 61.00253043 37.73394391 35.60241186 17.44185896
  79.00718944  4.86954282 45.03013173 54.02027316]
 [45.96681087 87.52452889 73.3153696  96.9129763  31.13487803 71.87329932
   1.82521957 58.42655413 19.03146106 30.3656908 ]
 [25.8257177  46.91199715 38.12329325 47.66697188 82.60893179 49.25303385
  98.0079396  32.24070524  3.15251564 56.393

In [17]:
# 14. Create a random vector of size 30 and find the mean value
random_number_generator = np.random.default_rng()
randomx30 = random_number_generator.random(size=(30)) * 10
print('random size 30 vector: ', randomx30)
mean = np.mean(randomx30)
print('mean: ' , mean)


random size 30 vector:  [4.47350926 6.89412054 4.96531904 9.75611681 3.42418103 5.28915918
 5.63875825 3.21628658 2.57244709 3.5553146  3.28466803 2.68845745
 2.59113385 8.23281663 1.23456932 8.76264124 2.6410933  3.05712328
 2.16666969 2.44424858 0.84488318 0.18558146 9.46356571 4.75603249
 1.95759592 6.9246435  4.55661271 0.06423449 4.84155804 6.74461523]
mean:  4.240931882818069


In [18]:
#Create a 2d array with 1 on the border and 0 inside
arr = np.arange(10, 30)
arr[:5]

array([10, 11, 12, 13, 14])