In [19]:
#broadcasting defines how numpy treats arrays of different sizes durign arithmetic operations
"""
operations on 2 numpy arrays are usually done on an element to element basis
-NumPy's broadcasting rule relaxes this constraint when the array's shape meets certain criteria

General Broadcasting rules
- When operating 2 arrays, numpy compares their shapes element wise
- It starts with the trailing dimension (right most dimension) {Dimensions are the number of indices required to access a specific element of a numpy array}
- arr = np.zeros((2, 3, 4))
    # Shape is (2, 3, 4)
    # Rightmost dimension is 4 (size of axis 2)
- Two dimensions are compatible if both are equal or  one of them is 1

"""



"\noperations on 2 numpy arrays are usually done on an element to element basis\n-NumPy's broadcasting rule relaxes this constraint when the array's shape meets certain criteria\n"

In [17]:
import numpy as np

In [18]:
#operations in numpy arrays are ususally done on an element to element basis
a = np.array([1,2,3])
b =  np.array([1,0,0])
a + b


array([2, 2, 3])

In [39]:
# simplest broadcasting- scalar and array combined in an operation
a = np.arange(5)
b = 1.1
b * a

array([0. , 1.1, 2.2, 3.3, 4.4])

In [48]:
a = np.arange(5)
b = np.array([1.1])
b * a

array([0. , 1.1, 2.2, 3.3, 4.4])

In [52]:
#not broadcastable
x = np.arange(4) # x => (4,)
y = np.arange(3) # y => (3,)
try:
    x + y
except:
    print("ValueError: operands could not be broadcast together with shapes (4,) (3,)")

ValueError: operands could not be broadcast together with shapes (4,) (3,)


In [54]:
a =  np.ones((4,3))
b = np.array([10,20,30])
# a =>(4,3)  ----- b => (3,)
a + b # (4,3)
(a+b).shape

(4, 3)

In [55]:
a = np.arange(6).reshape((2,3))
b = np.array([[100],[200]]) # (2,1)
a + b

array([[100, 101, 102],
       [203, 204, 205]])

In [56]:
row_vector = np.arange(3) #(3,)
column_vector = np.arange(3).reshape((3,1))
row_vector * column_vector

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [58]:
try:
    a = np.ones((3, 4))   # shape (3, 4)
    b = np.ones((2, 5))   # shape (2, 5)
    result = a + b
except:
    print('error')

error
